### ISSUE TITLE
`EndPipeFrame` class is used but not defined

### ISSUE THREAD

**Issue by amacapri** [pipecat-ai/pipecat#287]
`EndPipeFrame` class does not exist, but it is referenced from `src/pipecat/pipeline/merge_pipeline.py` and `examples/foundational/04-utterance-and-speech.py`.

**Comment by jptaylor** [comment]
Thank you. I think this a remnant and should be `EndFrame`. I think the foundational examples need a scan. Will try to get to this next week whilst we're updating docs.

**Comment by vipyne** [comment]
I believe this is resolved.  closing the issue.

**Comment by dominikroblek** [comment]
A quick search show the issue is not resolved:
https://github.com/search?q=repo%3Apipecat-ai%2Fpipecat%20EndPipeFrame&type=code

EndPipeFrame is not defined but still used by two examples.
